apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-k8s-deployment
  namespace: deployment-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-k8s
  template:
    metadata:
      labels:
        app: springboot-k8s
    spec:
      containers:
        - name: springboot-k8s
          image: springboot-k8s-example:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-k8s-service
  namespace: service-namespace
spec:
  type: LoadBalancer
  selector:
    app: springboot-k8s
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080